In [28]:
import numpy as np
import gym
from buffer import Buffer

env = gym.make('CartPole-v1')

dim_states = env.observation_space.shape[0]
continuous_control = isinstance(env.action_space, gym.spaces.Box)
dim_actions = env.action_space.shape[0] if continuous_control else env.action_space.n

buffer = Buffer(dim_states=dim_states, dim_actions=dim_actions, max_size = 12, sample_size = 4, continuous_control=continuous_control, drop_last=False, shuffle = True)

ob_t = env.reset()
for _ in range(10):
    
    act_t = env.action_space.sample()
    
    ob_t1, rew_t, done, _ = env.step(act_t)
    
    experience = ob_t, act_t, ob_t1
    
    buffer.store_transition(*experience)
    
    ob_t = ob_t1
    
    if done:
        ob_t = env.reset()

In [30]:
batches = buffer.get_batches()

n_batches = len(batches)
print(n_batches)

batches

3


[(array([[ 0.0264977 , -0.1531916 ,  0.00527109,  0.25160995],
         [ 0.00970173,  0.23503207,  0.03581439, -0.28941116],
         [ 0.02427096, -0.15341349,  0.00951517,  0.25651011],
         [ 0.00889285,  0.0404441 ,  0.03598027, -0.00829405]]),
  array([[0., 1.],
         [1., 0.],
         [0., 1.],
         [0., 1.]]),
  array([[ 0.02343387,  0.04185469,  0.01030329, -0.03940571],
         [ 0.01440237,  0.0394182 ,  0.03002617,  0.01434865],
         [ 0.02120269,  0.04157133,  0.01464538, -0.03315645],
         [ 0.00970173,  0.23503207,  0.03581439, -0.28941116]])),
 (array([[ 0.02565734,  0.04201773,  0.00613111, -0.04300106],
         [ 0.02120269,  0.04157133,  0.01464538, -0.03315645],
         [ 0.02343387,  0.04185469,  0.01030329, -0.03940571],
         [ 0.01895897, -0.34907624,  0.01926447,  0.56117111]]),
  array([[1., 0.],
         [1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[ 0.0264977 , -0.1531916 ,  0.00527109,  0.25160995],
         [ 0.02203

In [ ]:
rows = np.random.permutation(len(buffer._a_t_array))

a = buffer._a_t_array[rows].copy()

In [ ]:
buffer._a_t_array[rows]

In [ ]:
a[0] = np.nan
a